<?xml version='1.0' encoding='UTF-8'?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_TargetCryoYPosition" Id="{ed8d9bbf-f8b8-4c81-ba4e-45131b32819a}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION F_TargetCryoYPosition : LREAL
VAR_INPUT
    fNeutralPosition : LREAL;
    fBraidDiameter   : LREAL;
    fPhiAngleDeg     : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetCryoYPosition := fNeutralPosition - ABS(fBraidDiameter * (1 - Cos(fPhiAngleDeg * 3.1415 / 180)));
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>