<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_1_PlcTask" Id="{ffe71f0c-bf77-4cce-b8e1-24b1bdf50732}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_2_PMPS();
PRG_3_LOG();
PRG_SSL();
PRG_Diffractometer();
PRG_LAS();
PRG_SDS();
//PRG_RotDet();
//PRG_Questar();
PRG_SpetrometerArm();
PRG_Cryo();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>